name: 'cas unsupport'
description: 'Uses the cas CLI to unsupport digital assets, docker images and their SBOM'
branding:
  icon: 'lock'
  color: 'green'
inputs:
  asset:
    description: 'Asset to unsupport'
    required: true
  cas_api_key:
    description: 'API Key provided upon signing up through cas.codenotary.com'
    required: true
runs:
  using: 'docker'
  image: 'docker://codenotary/cas:bom-docker'
  args:
    - unsupport
    - ${{ inputs.asset }}
    - --api-key=${{ inputs.cas_api_key }}
    - --host=cas.codenotary.com
