name: unsupport a docker image sbom

on:
  push:
    branches: [main]

jobs:
  unsupport-docker-image-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Pull image
        run: docker pull codenotary/cas:bom-docker
        shell: bash


      - name: unsupport a Docker image
        #--> Run the GitHub action
        #
        uses: codenotary/cas-unsupport-asset-github-action@main
        with:
          # unsupport the image we pulled in the first step 
          asset: docker://codenotary/cas:bom-docker
          cas_api_key: ${{ secrets.CAS_API_KEY }}
